#!/bin/sh
dbus-send \
  --print-reply --session \
  --dest=org.mpris.MediaPlayer2.spotify \
  /org/mpris/MediaPlayer2 \
  org.freedesktop.DBus.Properties.Get \
  string:'org.mpris.MediaPlayer2.Player' \
  string:'Metadata' \
| awk '/xesam:title/ {getline; title=substr($0, index($0, $3))} /xesam:artist/ {getline; getline; artist=substr($0, index($0, $2))} END { print title " - " artist}' \
| tr -d '"'
